---
sudo: required

env:
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:
  - 'sudo docker run --detach --volume="$PWD":/etc/ansible/roles/role_under_test:ro ubuntu-14.04:ansible /sbin/init'

  - 'container_id=`docker ps -q`'
  - >
    docker exec "$container_id" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml 
  #  | grep -q 'ok=8.*changed=5.*failed=0'
  #  && (echo 'execution test: pass' && exit 0)
  #  || (echo 'execution test: fail' && exit 1)

  - >
    docker exec "$container_id" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml 
  #  | grep -q '*changed=0.*failed=0'
  #  && (echo 'idempotence test: pass' && exit 0)
  #  || (echo 'idempotence test: fail' && exit 1)

  - 'docker ps -aq | xargs docker kill'
  - 'docker ps -aq | xargs docker rm'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
